-- ============================================================================
-- CAPA GOLD: DIMENSIÓN DE PROVEEDORES (dim_vendors)
-- ============================================================================
CREATE TABLE IF NOT EXISTS dev.gold.dim_vendors (
    vendor_id INT COMMENT 'Unique vendor identifier (Primary Key)',
    vendor_name STRING COMMENT 'Company name of the taxi technology provider'
)
USING DELTA
COMMENT 'Capa Gold: Dimensión estática de proveedores de tecnología de taxímetros (CMT / VeriFone).';

-- ============================================================================
-- CAPA GOLD: TABLA DE HECHOS CENTRALIZADA DE VIAJES (fct_trips)
-- ============================================================================
CREATE TABLE IF NOT EXISTS dev.gold.fct_trips (
    -- Identificadores y Claves
    trip_id STRING COMMENT 'Unique trip identifier (Surrogate Key generated by hash)',
    vendor_id INT COMMENT 'Taxi technology provider ID',
    service_type STRING COMMENT 'Type of taxi service (Green or Yellow)',
    rate_code_id INT COMMENT 'Final rate code applied at the end of the trip',    
    -- Ubicaciones de Inicio (Origen)
    pickup_location_id INT COMMENT 'TLC Taxi Zone ID where the trip started',
    pickup_borough STRING COMMENT 'NYC borough name where the trip started',
    pickup_zone STRING COMMENT 'Specific TLC zone name where the trip started',    
    -- Ubicaciones de Fin (Destino)
    dropoff_location_id INT COMMENT 'TLC Taxi Zone ID where the trip ended',
    dropoff_borough STRING COMMENT 'NYC borough name where the trip ended',
    dropoff_zone STRING COMMENT 'Specific TLC zone name where the trip ended',    
    -- Tiempos y Duración
    pickup_datetime TIMESTAMP COMMENT 'Timestamp when the meter was engaged',
    dropoff_datetime TIMESTAMP COMMENT 'Timestamp when the meter was disengaged',
    trip_duration_minutes BIGINT COMMENT 'Calculated trip duration in minutes (dropoff - pickup)',    
    -- Detalles e Indicadores del Viaje
    store_and_fwd_flag STRING COMMENT 'Trip record stored in vehicle memory before uploading (Y/N)',
    passenger_count INT COMMENT 'Number of passengers in the vehicle',
    trip_distance DECIMAL(10, 2) COMMENT 'Trip distance in miles reported by the taximeter',
    trip_type INT COMMENT 'Trip type code (1=Street-hail, 2=Dispatch)',    
    -- Desglose Económico Monetario
    fare_amount DECIMAL(10, 2) COMMENT 'Time and distance fare calculated by the meter',
    extra DECIMAL(10, 2) COMMENT 'Miscellaneous extras and surcharges (rush hour, overnight)',
    mta_tax DECIMAL(10, 2) COMMENT '$0.50 MTA tax automatically triggered based on meter rate',
    tip_amount DECIMAL(10, 2) COMMENT 'Tip amount (Credit card tips only, cash not included)',
    tolls_amount DECIMAL(10, 2) COMMENT 'Total amount of all tolls paid during the trip',
    ehail_fee DECIMAL(10, 2) COMMENT 'E-hail service fee (Applies to Green Taxis only)',
    improvement_surcharge DECIMAL(10, 2) COMMENT 'Improvement surcharge assessed on hailed trips',
    total_amount DECIMAL(10, 2) COMMENT 'Total amount charged to passengers (excludes cash tips)',    
    -- Información de Pago Enriquecida
    payment_type INT COMMENT 'Payment method code',
    payment_type_description STRING COMMENT 'Human-readable payment method description (Enriched)'
)
USING DELTA
CLUSTER BY (pickup_datetime, service_type, pickup_borough) -- ⚡ Optimiza los queries analíticos mensuales de BI.
COMMENT 'Capa Gold: Tabla de hechos unificada y enriquecida con información geográfica y descripciones de pago.';

-- ============================================================================
-- CAPA GOLD: MART DE AGREGACIÓN DE INGRESOS MENSUALES (Reporting / Marts)
-- ============================================================================
CREATE TABLE IF NOT EXISTS dev.gold.fct_monthly_zone_revenue (
    -- Claves de la combinación única (Granularidad del reporte)
    pickup_zone STRING COMMENT 'Pickup zone where revenue was generated (TLC Zone Name)',
    revenue_month STRING COMMENT 'Month for revenue aggregation in format YYYY-MM',
    service_type STRING COMMENT 'Service type (Green or Yellow)',    
    -- Métricas del Negocio / KPIs Precalculados
    revenue_monthly_total_amount DECIMAL(14, 2) COMMENT 'Monthly sum of total fares and amounts charged',
    total_monthly_trips BIGINT COMMENT 'Total count of trips completed in the month',    
    -- Control de Auditoría
    calculated_at TIMESTAMP COMMENT 'Fecha y hora en la que PySpark calculó esta agregación comercial'
)
USING DELTA
CLUSTER BY (revenue_month, service_type) -- ⚡ Optimización para que los filtros de dashboards mensuales vuelen
COMMENT 'Capa Gold (Reporting): Resumen analítico mensual de ingresos y volumen de viajes por zona de recogida y tipo de taxi.';